### ISSUE TITLE
飞猫云2.2.6无法解析地址

### ISSUE THREAD

**Issue by dyhuan1** [lzyAB/link-helper#12]
飞猫云2.2.6无法解析地址，点击验证码后在自动解析处卡住。
已更新脚本，删除后自定义添加脚本故障依旧。

**Comment by lzyAB** [comment]
F12 打开开发者控制台 然后重新解析 截图控制台 Console 选项卡截图

**Comment by ookuralumine** [comment]
> F12 打开开发者控制台 然后重新解析 截图控制台 Console 选项卡截图

确实不能用了，点完验证码直接让重新登陆
![image](https://user-images.githubusercontent.com/24876569/197519278-c597a7d5-e94d-44df-8a2d-8f1442f110db.png)

**Comment by lzyAB** [comment]
> > F12 打开开发者控制台 然后重新解析 截图控制台 Console 选项卡截图
> 
> 确实不能用了，点完验证码直接让重新登陆 ![image](https://user-images.githubusercontent.com/24876569/197519278-c597a7d5-e94d-44df-8a2d-8f1442f110db.png)

该错误已修复，请重试

**Comment by dyhuan1** [comment]
已修复，作者大大速度真快，楼上刚上传Console数据，这边就修复了。牛皮！

**Comment by ookuralumine** [comment]
> > > F12 打开开发者控制台 然后重新解析 截图控制台 Console 选项卡截图
> > 
> > 
> > 确实不能用了，点完验证码直接让重新登陆 ![image](https://user-images.githubusercontent.com/24876569/197519278-c597a7d5-e94d-44df-8a2d-8f1442f110db.png)
> 
> 该错误已修复，请重试

卧槽，是真的快。突然就可以用了，感谢dalao
