### ISSUE TITLE
访问后端服务器错误

### ISSUE THREAD

**Issue by foamdemo** [lzyAB/link-helper#14]
如图
![CJ{CFGMP$R{J6LJ5(77XZ~6](https://user-images.githubusercontent.com/116860679/198497284-945d4f89-822b-42ca-be4d-ae68916a69a3.png)

**Comment by lzyAB** [comment]
关闭代理或开启代理

**Comment by foamdemo** [comment]
> 关闭代理或开启代理

意思是要挂梯子才行吗

**Comment by lzyAB** [comment]
可以试试 因为服务器使用了国外cdn 但是一般不需要
