### ISSUE TITLE
老哥，星耀云解析链接成功，弹打开链接失败

### ISSUE THREAD

**Issue by National777** [lzyAB/link-helper#18]
![_98UFESR2YO1F8NED3 @HT5](https://user-images.githubusercontent.com/114747659/199401602-7809646b-e83b-47b6-88dd-e8fca6a9d33d.png)

**Comment by lzyAB** [comment]
这是星耀云的问题，他们服务器挂了，等待星耀云恢复就行了。

**Comment by National777** [comment]
谢谢

lzyAB ***@***.***> 于 2022年11月2日周三 下午7:41写道：
