### ISSUE TITLE
飞猫云无法获取下载地址

### ISSUE THREAD

**Issue by Kreator33** [lzyAB/link-helper#19]
- 描述你的错误: 飞猫云无法正确获取下载地址，无任何提示。
- 在哪个页面发生的: https://www.feimaoyun.com/s/6ku8tobt
- 版本号: 2.2.7
- 油猴版本: Tampermonkey 4.16.1
- 浏览器: Google Chrome 107.0.5304.88（正式版本） （64 位）
- 开发者控制台截图: 
![20221105143022.ElFRWSLf-.png](https://api.onedrive.com/v1.0/shares/s!AhAGEbrlUqUbtwS483t2KH2kEuqN/root/content)

**Comment by lzyAB** [comment]
我们服务器受到了ddos攻击，我们会将服务转移，请耐心等待

**Comment by lzyAB** [comment]
请在github中更新脚本，并使用代理来辅助脚本运行
