### ISSUE TITLE
访问后端服务错误

### ISSUE THREAD

**Issue by Aliceikkk** [lzyAB/link-helper#20]
在飞猫云解析时出现访问后端错误
链接：https://www.feimaoyun.com/s/o9gjlclc
版本号.2.2.8
油猴版本号：4.18.0
用的Edge浏览器

![})B(RTQ6V2$B~%2@XHXEOWS](https://user-images.githubusercontent.com/115286672/200125193-6d9b43d5-5d3c-4530-b160-39699154f9da.png)

**Comment by lzyAB** [comment]
使用代理访问，或等待下个版本的更新。
