### ISSUE TITLE
访问后端服务错误公众号解决方案都试了，除了用谷歌

### ISSUE THREAD

**Issue by DSP123-boop** [lzyAB/link-helper#21]
[](url)### - 描述你的错误:访问后端服务错误，请重试
- 在哪个页面发生的:飞猫云
- 版本号:2.2.9
- 油猴版本:最新
- 浏览器:火狐、狐猴、Edge
- 开发者控制台截图:
![屏幕截图 2022-11-10 165212](https://user-images.githubusercontent.com/117900291/201045751-0a51e628-c8da-45a8-bd88-7164ce9fb2e8.png)

**Comment by lzyAB** [comment]
使用代理尝试
