### ISSUE TITLE
提示获取下载链接完成，点击下载提示请获取下载地址

### ISSUE THREAD

**Issue by Allen2119** [lzyAB/link-helper#23]
描述你的错误:提示获取下载链接完成，点击下载提示请获取下载地址
在哪个页面发生的:飞猫云
版本号:空城里链接助手 - version:2.2.9
油猴版本:Tampermonkey 4.18.0
浏览器:谷歌浏览器，360极速浏览器
开发者控制台截图:
![QQ截图20221118164256](https://user-images.githubusercontent.com/49140418/202659566-237c0a15-fdb4-44fc-87d5-170936031ce5.png)

**Comment by Allen2119** [comment]
翻墙和不翻都是同样的。

**Comment by sd2450350** [comment]
描述你的错误:提示获取下载链接完成，点击下载提示请获取下载地址
在哪个页面发生的:飞猫云
版本号:空城里链接助手 - version:2.2.9
油猴版本:Tampermonkey 4.18.1
浏览器:谷歌浏览器，冰鼬下载器
开发者控制台截图:
![图片](https://user-images.githubusercontent.com/118592573/202839415-cbca2058-d61e-436f-8843-fd08ebc33a11.png)
![图片](https://user-images.githubusercontent.com/118592573/202839504-1b151898-df86-452b-8322-4afa9f104bb1.png)
