### ISSUE TITLE
点击“点击下载”后出现“请先获取下载地址”，无法正常下载

### ISSUE THREAD

**Issue by HarryLinner** [lzyAB/link-helper#24]
- 描述你的错误:(点击“点击下载”后出现“请先获取下载地址，无法正常下载”)
- 在哪个页面发生的:([[这里提供错误页面的链接地址](https://www.feimaoyun.com/s/iycmnnra)](https://www.feimaoyun.com/s/iycmnnra))
- 版本号:(2.2.9)
- 油猴版本:(v4.18.0)
- 浏览器:(google)
- 开发者控制台截图:(你需要提供
![]()
![1668761007620](https://user-images.githubusercontent.com/114590874/202659543-6a2875b1-38ab-4dc9-a114-57c0e50163f9.png)

**Comment by pleasecall** [comment]
我也有同样的问题

**Comment by lierihawk** [comment]
遇到同样的问题

**Comment by Xiaodu116** [comment]
+1

**Comment by 365111722** [comment]
+1 同样的情况

**Comment by xuerbujia** [comment]
+1

**Comment by xuerbujia** [comment]
+1
浏览器 Chrome
版本号 2.2.9

**Comment by phwhpw** [comment]
+1
浏览器 Chrome
版本号 2.2.9

**Comment by wanquliaoQ** [comment]
寄了！飞猫盘限制一天300次

**Comment by Zmzzd** [comment]
同样问题

**Comment by menghuiqiange** [comment]
遇到同样的问题，要求下载地址
版本号:(2.2.9)
油猴版本：（v4.16.1）
浏览器：[Edge]

**Comment by Game-angel** [comment]
+1 相同的情况

**Comment by sd2450350** [comment]
描述你的错误:提示获取下载链接完成，点击下载提示请获取下载地址
在哪个页面发生的:飞猫云
版本号:空城里链接助手 - version:2.2.9
油猴版本:Tampermonkey 4.18.1
浏览器:谷歌浏览器，冰鼬浏览器
开发者控制台截图:
![图片](https://user-images.githubusercontent.com/118592573/202839415-cbca2058-d61e-436f-8843-fd08ebc33a11.png)
![图片](https://user-images.githubusercontent.com/118592573/202839504-1b151898-df86-452b-8322-4afa9f104bb1.png)

**Comment by wider00chen** [comment]
[我还以为只有我直接是

![003](https://user-images.githubusercontent.com/118594419/202840935-c5704103-17b6-4689-ac62-acc9e54f7761.png)

**Comment by mana-alice** [comment]
![B1GFQC)3F7I{X_~GJD`HELL](https://user-images.githubusercontent.com/118598844/202844580-474a949c-cca7-4c6d-823e-9c84b255d8ed.png)
