### ISSUE TITLE
提示：请先登录！请刷新界面！

### ISSUE THREAD

**Issue by aBREATHLESSz** [lzyAB/link-helper#25]
- 描述你的错误:(最短的话将它描述出来)
- 在哪个页面发生的:(这里提供错误页面的链接地址)
- 版本号:(你所使用的脚本版本号)
- 油猴版本:(你所使用的油猴版本)
- 浏览器:(你所使用的浏览器)
- 开发者控制台截图:(你需要提供一张或多张控制台信息截图,请在出现错误前打开控制台,以方便记录所有日志,不要吝啬一张图片,你可以将它更完整)

**Comment by lzyAB** [comment]
我们的会员账号被封禁了 : (

**Comment by lzyAB** [comment]
![HQZR6X8E$(@3(200R)M0 4](https://user-images.githubusercontent.com/89786902/203261726-1e13d8c2-84b6-43c4-b8fa-df7e0531443a.jpg)

**Comment by 1778998158** [comment]
感谢大佬，辛苦大佬了，耐心等大佬安排，谢谢大佬！！！

**Comment by disansj** [comment]
呜呜呜 辛苦了
