### ISSUE TITLE
填写验证码后，显示自动开始自动解析就不动了

### ISSUE THREAD

**Issue by secret-deus** [lzyAB/link-helper#29]
- 描述你的错误:(无法解析)
- 在哪个页面发生的:(https://www.feimaoyun.com/s/c7gkn1hn)
- 版本号:(2.3.1)
- 油猴版本:(4.16.1)
- 浏览器:(edge)
- 开发者控制台截图:(![image](https://user-images.githubusercontent.com/73240031/203471544-92c7f975-410a-476f-9cfc-653698121742.png))

**Comment by lzyAB** [comment]
重新尝试

**Comment by disansj** [comment]
重试也不行。。
