### ISSUE TITLE
验证成功后没有开始下载 点下载无反应

### ISSUE THREAD

**Issue by liujeffqi** [lzyAB/link-helper#3]
![QQ截图20220922151210](https://user-images.githubusercontent.com/9792077/191860588-62b0949c-beef-4b4d-8a3c-58f65c0ce9ca.png)

**Comment by lzyAB** [comment]
如果开启了代理 请关闭代理后重试

**Comment by liujeffqi** [comment]
没有开代理 不过我是海外的是不是需要翻回去

**Comment by lzyAB** [comment]
尝试在脚本代码如下地方添加

```javascript
console.log(res)
```
并查看控制台输出信息


![image](https://user-images.githubusercontent.com/89786902/191884440-2146d700-8c36-4282-925d-afe3438f17da.png)

**Comment by liujeffqi** [comment]
输出的log文件 
[www.feimaoyun.com-1663905007900.log](https://github.com/lzyAB/link-helper/files/9630628/www.feimaoyun.com-1663905007900.log)

在 console里的截图
![QQ截图20220922205150](https://user-images.githubusercontent.com/9792077/191889214-8c009195-7f99-41d5-af5c-3e36dd249835.png)

**Comment by lzyAB** [comment]
多次尝试 这是由于cloudflare DNS解析引起的

**Comment by liujeffqi** [comment]
好的 我再多试试

**Comment by liujeffqi** [comment]
应该还是海外IP的问题。 我翻回国就好了
