### ISSUE TITLE
2.3.1版本脚本无法正常解析地址

### ISSUE THREAD

**Issue by md123zz** [lzyAB/link-helper#30]
- 描述你的错误:2.3.1版本脚本无法正常解析地址
- 在哪个页面发生的:https://www.feimaoyun.com/s/10i18jyr
- 版本号:2.3.1
- 油猴版本:4.18.1
- 浏览器:Microsoft Edge
- 开发者控制台截图:(
![image](https://user-images.githubusercontent.com/118880823/203491184-52737337-396c-4cf2-93c5-b93fa0bc26ba.png)
![image](https://user-images.githubusercontent.com/118880823/203491247-5949d728-fb2b-4297-856b-863108cf6b57.png)
![image](https://user-images.githubusercontent.com/118880823/203491331-e3222dcc-c9b8-4688-a89d-77d68dfe0eb4.png)
)

**Comment by disansj** [comment]
我的也是 刷新了一下午没成功一次

**Comment by lzyAB** [comment]
刚买的服务器IP被ban了 请求量太大了 :(

**Comment by md123zz** [comment]
不管能不能维修好，依旧向为爱奉献的大佬致敬。

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by disansj** [comment]
大大辛苦了
 &nbsp;
  
      
  多餘dē絗憶&nbsp;
 ***@***.***



 &nbsp;
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人: "lzyAB/link-helper" ***@***.***&gt;;
 发送时间:&nbsp;2022年11月23日(星期三) 下午5:21
 ***@***.***&gt;;
 抄送:&nbsp;"多餘dē絗憶 ***@***.******@***.***&gt;;
 主题:&nbsp;Re: [lzyAB/link-helper] 2.3.1版本脚本无法正常解析地址 (Issue #30)

 

 

 
刚买的服务器IP被ban了 请求量太大了 :(

**Comment by StarLi-zh** [comment]
请问迅牛能用这个吗？我试了一下报错诶

**Comment by ShihuogegeTech** [comment]
![image](https://user-images.githubusercontent.com/66984287/203534761-5114428f-2254-4990-af93-997db4647602.png)
剛試了下 最新版也是報錯QQ

**Comment by lzyAB** [comment]
我们已经修复无法解析的错误，请重新尝试即可。

**Comment by senekiproxy** [comment]
刚试了下好像还是不行呃
[<a href="https://imgse.com/i/z8bgW4"><img src="https://s1.ax1x.com/2022/11/23/z8bgW4.png" alt="z8bgW4.png" border="0" /></a>](url)

**Comment by lzyAB** [comment]
> 刚试了下好像还是不行呃 [![z8bgW4.png](https://camo.githubusercontent.com/28ce462e679632c68f9c4f3eca0c0535d8b8c8584ba01d97044f081c3b6c9afb/68747470733a2f2f73312e617831782e636f6d2f323032322f31312f32332f7a38626757342e706e67)](https://imgse.com/i/z8bgW4)

清除浏览器缓存?升级脚本?

**Comment by senekiproxy** [comment]
> > 刚试了下好像还是不行呃 [![z8bgW4.png](https://camo.githubusercontent.com/28ce462e679632c68f9c4f3eca0c0535d8b8c8584ba01d97044f081c3b6c9afb/68747470733a2f2f73312e617831782e636f6d2f323032322f31312f32332f7a38626757342e706e67)](https://imgse.com/i/z8bgW4)
> 
> 清除浏览器缓存?升级脚本?

清缓存后就可以了，谢谢大哥
