### ISSUE TITLE
2.3.1版本解析后提示登录

### ISSUE THREAD

**Issue by lolp521** [lzyAB/link-helper#32]
描述你的错误:2.3.1版本解析后提示登录
在哪个页面发生的:[(https://www.feimaoyun.com/s/xwdfxnyy)]
版本号:(2.3.1)
油猴版本:(4.16.1)
浏览器:(Microsoft Edge)
@##开发者控制台截图:
![image](https://user-images.githubusercontent.com/60544439/203891389-75d41228-7d2e-4444-8ab4-233f853cc9c9.png)

**Comment by lzyAB** [comment]
重新尝试，账号被封禁了。

**Comment by tudou88** [comment]
貌似又这样了,估计账号又被封了,看来飞猫真的太可恶了.

**Comment by lzyAB** [comment]
已经恢复了，目前被封了5个号了 :(

**Comment by tudou88** [comment]
> 已经恢复了，之前被封了5个号了:(

谢谢了 大佬是不是你那边没有调测好,这样封的有点夸张

**Comment by lzyAB** [comment]
> > 已经恢复了，之前被封了5个号了:(
> 
> 谢谢了 大佬是不是你那边没有调测好,这样封的有点夸张

请求量太大了，1分钟几十次的下载，每次解析的文件都不一样，云存储起不到多大效果

**Comment by tudou88** [comment]
> > > 已经修复了，之前被封了5个号了:(
> > 
> > 
> > 谢谢了 大佬不是你那边没有调测好,这种封的有点夸张
> 
> 请要求量太大了，1分钟几十次的下载，每次解析的文件都不一样，云存储起不到多大效果
不如开始收费好了便宜点 杜绝大多数白嫖

**Comment by 81TCH35** [comment]
账号又挂了 @tudou88

**Comment by lunaticex** [comment]
> > > 已经恢复了，之前被封了5个号了:(
> > 
> > 
> > 谢谢了 大佬是不是你那边没有调测好,这样封的有点夸张
> 
> 请求量太大了，1分钟几十次的下载，每次解析的文件都不一样，云存储起不到多大效果

飞猫也像其他盘一样弄个众筹吧

**Comment by BBBBBeiyu** [comment]
同意参与众筹

**Comment by L-otus** [comment]
又被封禁了，太难了

**Comment by HLJJ** [comment]
来点众筹，而且好像听说vip每天只有300的下载次数

**Comment by 1778998158** [comment]
飞猫脸都不要了，无耻

**Comment by disansj** [comment]
宁愿花钱在解析上也不去冲飞猫盘会员 呸

**Comment by mana-alice** [comment]
现在还是用不了啊，作者大大我支持众筹

**Comment by pleasecall** [comment]
网赚盘都是这个尿性，很恶心

**Comment by xxwrt** [comment]
可以众筹+1
其实我可以接受网赚盘广告多下载慢，反正后台挂就完事了
但飞猫直接不让下真的恶心
众筹出了踢我一下，搞点天卡次卡什么的

**Comment by ngzx86** [comment]
众筹+1

**Comment by as0101** [comment]
还是众筹吧，飞猫真的恶心

**Comment by dreammaker521** [comment]
众筹+1
