### ISSUE TITLE
需要为开发者提供一个下载会提示资源过期的文件

### ISSUE THREAD

**Issue by lzyAB** [lzyAB/link-helper#34]
为开发者提供一个下载会提示资源过期的某猫云文件。

**Comment by Qianqianyuya** [comment]
http://www.fmpan.com/#/s/6hydjiti

**Comment by Qianqianyuya** [comment]
> 为开发者提供一个下载会提示资源过期的某猫云文件。

http://www.fmpan.com/#/s/6hydjiti
