### ISSUE TITLE
关于验证码

### ISSUE THREAD

**Issue by xxwrt** [lzyAB/link-helper#36]
- 主题:(哪个方面)
- 细嗦:(详细嗦嗦)
- 代码:(若你可以对脚本进行一些使用上的优化，请在此加入优化的代码)
如果我是飞猫老板，那我自己肯定知道自己验证码是啥啊，还是可以定向爆破账号
加个别的验证码系统吧
感觉保险一点

**Comment by lzyAB** [comment]
验证码是飞猫的 不是脚本的 :)
