### ISSUE TITLE
如图

### ISSUE THREAD

**Issue by lmlx001** [lzyAB/link-helper#6]
> @
![屏幕截图 2022-10-18 123632](https://user-images.githubusercontent.com/109841067/196336637-25469f48-7985-4bcc-b516-cded51fee120.png)
![屏幕截图 2022-10-18 123752](https://user-images.githubusercontent.com/109841067/196336706-69649fc5-cdd6-4b12-b2d7-c32255bedc11.png)

**Comment by lzyAB** [comment]
我们已对它进行了修复，他不会在油猴脚本中进行任何更新，请在github代码中使用raw更新

**Comment by lmlx001** [comment]
![屏幕截图 2022-10-18 210325](https://user-images.githubusercontent.com/109841067/196437367-375d66b8-caae-428e-94a0-55f32b21d074.png)

**Comment by lzyAB** [comment]
这是我们的疏忽，已经对此进行了修复，请在看到这条消息后重试
