### ISSUE TITLE
yifile无法获取下载链接 报错贴图如下

### ISSUE THREAD

**Issue by Lanmer** [lzyAB/link-helper#7]
![图片](https://user-images.githubusercontent.com/64339977/196618601-6951a614-630a-4cea-b3ae-fcb2ff1acccc.png)

**Comment by lzyAB** [comment]
请提供一下文件链接

**Comment by Lanmer** [comment]
> 请提供一下文件链接

https://www.yifile.com/f/VFcerwbc&a=1

**Comment by lzyAB** [comment]
![image](https://user-images.githubusercontent.com/89786902/196619832-89629695-1ebb-4d71-89bb-51799e4e8ca3.png)

请在此处添加该行代码，并重试
```javascript
console.log(res.response)
```

**Comment by lzyAB** [comment]
这是由于cloudflare DNS解析引起的问题，你可以尝试开启代理软件后重试，该问题暂时无法解决。

**Comment by Lanmer** [comment]
![图片](https://user-images.githubusercontent.com/64339977/196622258-bedb68d3-dc80-4b5b-84d7-95f0b08dd904.png)

长时间挂起，因第一次使用贵脚本，不太清楚获取链接所需时间，因怀疑网络环境问题，期间使用不同网络条件尝试，为同一情况

**Comment by lzyAB** [comment]
这是cloudflare DNS解析引起的问题，返回的response内容 为 time-out，因为cloudflare是国外的CDN服务商，所以我们无法解决该问题，另外，脚本并没有破解该网盘的VIP下载，所以不建议你使用脚本下载大文件。

脚本目前只支持 飞猫云、kufile这两个网盘高速下载。

其他网盘皆为免等待下载。

**Comment by Lanmer** [comment]
> 

非常感谢！
